export const NOTIF = {
  QUERY: 'QUERY',
  QUERY_RESULT: 'QUERY_RESULT',
  QUERY_F5: 'QUERY_F5',
  GET_PAGE_DATA: 'GET_PAGE_DATA',
  GET_PAGE_DATA_RESULT: 'GET_PAGE_DATA_RESULT'
};

export const QUERY_TYPE = {
  USER: 'USER',
  BACKGROUND: 'BACKGROUND'
};