export const NOTIF = {
  QUERY: 'QUERY',
  QUERY_RESULT: 'QUERY_RESULT',
  QUERY_F5: 'QUERY_F5'
};

export const QUERY_TYPE = {
  USER: 'USER',
  BACKGROUND: 'BACKGROUND'
};

export const VIEW_MODE = {
  PAGE_VIEWER: 'PAGE_VIEWER',
  CODE_EDITOR: 'CODE_EDITOR'
};